# Generated by Django 5.2.3 on 2025-08-16 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_seed_sdg_goals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImpersonationLog',
        ),
    ]
